// =============================================================================
// Supabase Database Types
// This file will be auto-generated by Supabase CLI: supabase gen types typescript
// For now, export a placeholder Database type
// =============================================================================

export type Database = {
  public: {
    Tables: Record<string, unknown>;
    Views: Record<string, unknown>;
    Functions: Record<string, unknown>;
  };
};
